# -*- coding: utf-8 -*-
"""Projeto calculadora .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EyyRMQKQc6YJQLH1gupjxwxmNkw-lxlc
"""

import re

operação = input("Que operação deseja fazer?")
conta = re.search(r'(\d+)(\+|\-|\*|\/)(\d+)',operação)

if conta:
  a = int(conta.group(1))
  b = str(conta.group(2))
  c = int(conta.group(3))

  if b == '+':
    resultado = a + c

  elif b == '-':
    resultado = a - c

  elif b == '*':
    resultado = a * c

  else:
    resultado = a / c

  print("O resultado de sua operação é:", resultado)

  while True:
    operação = input("Digite a operação (ou 'sair' para encerrar): ")

    if operação.lower() == "sair":
        print("Calculadora encerrada. Até logo!")
        break

    try:
        # usado para calcular expressões com várias operações
        resultado = eval(operação)
        print("O resultado da sua operação é:", resultado)

        # pergunta se o usuário quer continuar
        continuar = input("Deseja fazer outra operação? (s/n): ")
        if continuar.lower() != "s":
            print("Calculadora encerrada. Até logo!")
            break

    except Exception as e:
        print("Operação inválida, tente novamente!")